// priority: 0

console.info('Hello, World! (You will see this line every time server resources reload)')

ServerEvents.recipes(event => {
  //Helmet
  event.remove({id: 'twilightforest:equipment/knightmetal_helmet'})
  event.recipes.summoningrituals.altar("twilightforest:steeleaf_helmet")
  .itemOutput('twilightforest:knightmetal_helmet')
  .input('16x twilightforest:knightmetal_ingot')
  .input('8x twilightforest:knightmetal_block')
  .input('16x twilightforest:carminite')
  .input('8x twilightforest:carminite_block')
  .input('twilightforest:ur_ghast_trophy')
  .input('twilightforest:ur_ghast_trophy')
  .input('twilightforest:knight_phantom_trophy')
  .input('twilightforest:knight_phantom_trophy')
  .recipeTime(800)
  .blockBelow('twilightforest:knightmetal_block')
  //Chestplate
  event.remove({id: 'twilightforest:equipment/knightmetal_chestplate'})
  event.recipes.summoningrituals.altar("twilightforest:steeleaf_chestplate")
  .itemOutput('twilightforest:knightmetal_chestplate')
  .input('16x twilightforest:knightmetal_ingot')
  .input('8x twilightforest:knightmetal_block')
  .input('16x twilightforest:carminite')
  .input('8x twilightforest:carminite_block')
  .input('twilightforest:ur_ghast_trophy')
  .input('twilightforest:ur_ghast_trophy')
  .input('twilightforest:knight_phantom_trophy')
  .input('twilightforest:knight_phantom_trophy')
  .recipeTime(800)
  .blockBelow('twilightforest:knightmetal_block')
  //Leggings
  event.remove({id: 'twilightforest:equipment/knightmetal_leggings'})
  event.recipes.summoningrituals.altar("twilightforest:steeleaf_leggings")
  .itemOutput('twilightforest:knightmetal_leggings')
  .input('16x twilightforest:knightmetal_ingot')
  .input('8x twilightforest:knightmetal_block')
  .input('16x twilightforest:carminite')
  .input('8x twilightforest:carminite_block')
  .input('twilightforest:ur_ghast_trophy')
  .input('twilightforest:ur_ghast_trophy')
  .input('twilightforest:knight_phantom_trophy')
  .input('twilightforest:knight_phantom_trophy')
  .recipeTime(800)
  .blockBelow('twilightforest:knightmetal_block')
  //Boots
  event.remove({id: 'twilightforest:equipment/knightmetal_boots'})
  event.recipes.summoningrituals.altar("twilightforest:steeleaf_boots")
  .itemOutput('twilightforest:knightmetal_boots')
  .input('16x twilightforest:knightmetal_ingot')
  .input('8x twilightforest:knightmetal_block')
  .input('16x twilightforest:carminite')
  .input('8x twilightforest:carminite_block')
  .input('twilightforest:ur_ghast_trophy')
  .input('twilightforest:ur_ghast_trophy')
  .input('twilightforest:knight_phantom_trophy')
  .input('twilightforest:knight_phantom_trophy')
  .recipeTime(800)
  .blockBelow('twilightforest:knightmetal_block')
})