// priority: 0

console.info('Hello, World! (You will see this line every time server resources reload)')

ServerEvents.recipes(event => {
  //Helmet
  event.remove({id: 'twilightforest:equipment/fiery_fiery_helmet'})
  event.remove({id: 'twilightforest:equipment/fiery_helmet'})
  event.recipes.summoningrituals.altar("undergarden:utherium_helmet")
  .itemOutput('twilightforest:fiery_helmet')
  .input('16x twilightforest:fiery_ingot')
  .input('8x twilightforest:fiery_block')
  .input('twilightforest:hydra_trophy')
  .input('twilightforest:hydra_trophy')
  .input('twilightforest:minoshroom_trophy')
  .input('twilightforest:minoshroom_trophy')
  .recipeTime(800)
  .blockBelow('twilightforest:fiery_block')
  //Chestplate
  event.remove({id: 'twilightforest:equipment/fiery_fiery_chestplate'})
  event.remove({id: 'twilightforest:equipment/fiery_chestplate'})
  event.recipes.summoningrituals.altar("undergarden:utherium_chestplate")
  .itemOutput('twilightforest:fiery_chestplate')
  .input('16x twilightforest:fiery_ingot')
  .input('8x twilightforest:fiery_block')
  .input('twilightforest:hydra_trophy')
  .input('twilightforest:hydra_trophy')
  .input('twilightforest:minoshroom_trophy')
  .input('twilightforest:minoshroom_trophy')
  .recipeTime(800)
  .blockBelow('twilightforest:fiery_block')
  //Leggings
  event.remove({id: 'twilightforest:equipment/fiery_fiery_leggings'})
  event.remove({id: 'twilightforest:equipment/fiery_leggings'})
  event.recipes.summoningrituals.altar("undergarden:utherium_leggings")
  .itemOutput('twilightforest:fiery_leggings')
  .input('16x twilightforest:fiery_ingot')
  .input('8x twilightforest:fiery_block')
  .input('twilightforest:hydra_trophy')
  .input('twilightforest:hydra_trophy')
  .input('twilightforest:minoshroom_trophy')
  .input('twilightforest:minoshroom_trophy')
  .recipeTime(800)
  .blockBelow('twilightforest:fiery_block')
  //Boots
  event.remove({id: 'twilightforest:equipment/fiery_fiery_boots'})
  event.remove({id: 'twilightforest:equipment/fiery_boots'})
  event.recipes.summoningrituals.altar("undergarden:utherium_boots")
  .itemOutput('twilightforest:fiery_boots')
  .input('16x twilightforest:fiery_ingot')
  .input('8x twilightforest:fiery_block')
  .input('twilightforest:hydra_trophy')
  .input('twilightforest:hydra_trophy')
  .input('twilightforest:minoshroom_trophy')
  .input('twilightforest:minoshroom_trophy')
  .recipeTime(800)
  .blockBelow('twilightforest:fiery_block')
})