#Overrides all other config options for easy difficulty management
#This value is changed by the in-game config. It does nothing otherwise.
#Range: 0 ~ 4
Difficulty = 0

["Item settings"]
	#Allow fire resistance to block overheating damage
	"Fire Resistance Immunity" = true
	#Allow ice resistance to block freezing damage
	"Ice Resistance Immunity" = true
	#Thermometer item is required to see detailed world temperature
	"Require Thermometer" = false

["Misc temperature-related things"]
	#Sets whether damage scales with difficulty
	"Damage Scaling" = false
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Prevent Sleep When in Danger" = true

["Details about how the player is affected by temperature"]
	#Defines the minimum habitable temperature
	#Range: -Infinity ~ Infinity
	"Minimum Habitable Temperature" = 0.19047619047619047
	#Defines the maximum habitable temperature
	#Range: -Infinity ~ Infinity
	"Maximum Habitable Temperature" = 2.0952380952380953
	#Rate at which the player's body temperature changes (default: 1.0 (100%))
	#Range: 0.0 ~ Infinity
	"Rate Multiplier" = 0.3
	#Damage dealt to the player when they are too hot or too cold
	#Range: 0.0 ~ Infinity
	"Temperature Damage" = 1.0

["Temperature Effects"]

	["Temperature Effects".Hot]
		#When set to true, the player's view distance will decrease when they are too hot
		"Heatstroke Fog" = true

	["Temperature Effects".Cold]
		#When set to true, some of the player's hearts will freeze when they are too cold, preventing regeneration
		"Freezing Hearts" = true
		#When set to true, the player's attack knockback will be reduced when they are too cold
		"Cold Knockback Reduction" = true
		#When set to true, the player's movement speed will be reduced when they are too cold
		"Cold Slowness" = true
		#When set to true, the player's mining speed will be reduced when they are too cold
		"Cold Mining Fatigue" = true

["Grace Period Details"]
	#The number of ticks after the player spawns during which they are immune to temperature effects
	#Range: > 0
	"Grace Period Length" = 6000
	#Enables the grace period
	"Grace Period Enabled" = true

[Hearth]
	#How strong the hearth is
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.5
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "occultism:otherworld_leaves_natural", "primalmagick:moonwood_leaves", "minecraft:azalea_leaves", "ancient_aether:highsproot_leaves", "minecraft:oak_leaves", "primalmagick:hallowood_leaves", "forbidden_arcanus:aurum_leaves", "rats:pirat_leaves", "forbidden_arcanus:nuggety_aurum_leaves", "minecraft:mangrove_leaves", "aether:skyroot_leaves", "minecraft:acacia_leaves", "deep_aether:yagroot_leaves", "aether:golden_oak_leaves", "deep_aether:cruderoot_leaves", "solarcraft:radiant_leaves", "wizards_reborn:arcane_wood_leaves", "ars_nouveau:purple_archwood_leaves", "minecraft:birch_leaves", "primalmagick:sunwood_leaves", "minecraft:dark_oak_leaves", "blue_skies:maple_leaves", "aether_redux:blighted_skyroot_leaves", "deep_aether:roseroot_leaves", "blue_skies:starlit_leaves", "aether:decorated_holiday_leaves", "aether:crystal_leaves", "deep_aether:conberry_leaves", "blue_skies:frostbright_leaves", "blue_skies:crescent_fruit_leaves", "occultism:otherworld_leaves", "ars_nouveau:green_archwood_leaves", "solarcraft:ash_leaves", "blue_skies:dusk_leaves", "minecraft:jungle_leaves", "vinery:cherry_leaves", "minecraft:cherry_leaves", "aether:crystal_fruit_leaves", "blue_skies:bluebright_leaves", "blue_skies:comet_leaves", "ars_nouveau:blue_archwood_leaves", "vinery:grapevine_leaves", "minecraft:spruce_leaves", "aether_redux:blightwillow_leaves", "aether_redux:gilded_oak_leaves", "blue_skies:crystallized_leaves", "deep_aether:sunroot_leaves", "blue_skies:lunar_leaves", "aether:holiday_leaves", "ancient_aether:sakura_leaves", "deep_aether:yagroot_roots", "deep_aether:blue_roseroot_leaves", "vinery:apple_leaves", "deep_aether:flowering_roseroot_leaves", "minecraft:flowering_azalea_leaves", "ancient_aether:frosted_highsproot_leaves", "aether_redux:glacia_leaves", "ars_nouveau:red_archwood_leaves", "solarcraft:runic_leaves", "deep_aether:flowering_blue_roseroot_leaves"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

["Cold Soul Fire"]
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

