ServerEvents.recipes(event => {
//Moss Block
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:dandelion"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:poppy"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:blue_orchid"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:allium"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:azure_bluet"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:red_tulip"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:orange_tulip"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:white_tulip"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:pink_tulip"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:oxeye_daisy"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:cornflower"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:lily_of_the_valley"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:sunflower"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:lilac"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:rose_bush"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:peony"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:kelp"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:oxeye_daisy"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:flowering_azalea"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:spore_blossom"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:vine"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:lily_pad"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:kelp"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:seagrass"}})
event.custom({"type": "exnihilosequentia:sieve", "rolls":[{"chance":0.25,"mesh":"string"}],"input": {"item": "minecraft:moss_block"}, "result": {"item": "minecraft:dead_bush"}})
})