
#General settings
[General]
	#Chance of a Lunar Event happening when night falls [Default: 0.4]
	#Range: 0.0 ~ 1.0
	lunarEventChance = 0.1

#Event settings
[Events]
	#Weight of the Blood Moon Event [Default: 60]
	#Range: 0 ~ 100
	bloodMoonWeight = 10
	#Weight of the Crimson Moon Event [Default: 20]
	#Range: 0 ~ 100
	crimsonMoonWeight = 10
	#Weight of the Miner Moon Event [Default: 40]
	#Range: 0 ~ 100
	minerMoonWeight = 10
	#Weight of the White Moon Event [Default: 10]
	#Range: 0 ~ 100
	whiteMoonWeight = 10
	#Weight of the Tiny Moon Event [Default: 10]
	#Range: 0 ~ 100
	tinyMoonWeight = 0
	#Weight of the Big Moon Event [Default: 10]
	#Range: 0 ~ 100
	bigMoonWeight = 10
	#Weight of the Big Moon Event [Default: 5]
	#Range: 0 ~ 100
	badOmenMoonWeight = 0
	#Weight of the Hero Moon Event [Default: 5]
	#Range: 0 ~ 100
	heroMoonWeight = 0
	#Weight of the Eclipse Moon Event [Default: 2]
	#Range: 0 ~ 100
	eclipseMoonWeight = 10

#Crimson Replacement settings
[Crimson]
	#List of entities to replace during the Crimson Moon Event [Example: "minecraft:zombie,minecraft:zombified_piglin"]
	crimsonReplacements = ["minecraft:zombie,netherskeletons:crimson_skeleton", "minecraft:husk,netherskeletons:crimson_skeleton", "minecraft:skeleton,netherskeletons:crimson_skeleton", "minecraft:creeper,netherskeletons:crimson_skeleton", "minecraft:spider,netherskeletons:crimson_skeleton"]

