
["Mob's Strength and Weakness"]
	#Up to how much more health can mobs have? (%)
	health_increase = 250
	#Up to how much less health can mobs have? (%)
	health_decrease = 0
	#Up to how much more damage can mobs deal? (%)
	damage_increase = 100
	#Up to how much less damage can mobs deal? (%)
	damage_decrease = 0
	#Up to how much faster can mobs be? (%)
	speed_increase = 50
	#Up to how much slower can mobs be? (%)
	speed_decrease = 0

