
["Crack Hammer Durability"]
	copper = 64
	gold = 96
	iron = 128
	steel = 160
	diamond = 256
	netherite = 384

["Chisel Durability"]
	copper = 10
	gold = 15
	iron = 30
	steel = 45
	diamond = 64
	netherite = 96

["Scythe Harvest Radius"]
	# Range: 1 ~ 3 - Default: 1
	radius = 1

["Block and Mob Loot Settings"]
	# Determine the chance with which an item can drop from Ores and Mobs.
	#0.0 = 0% ~ 1.0 = 100%
	diamondNuggetFromDiamondOre = 0.15
	diamondNuggetFromCoalOre = 0.025
	garlicFromZombie = 0.2
	sulfurFromCreeper = 0.2
	saltpeterFromCreeper = 0.2
	saltpeterFromBricks = 0.5

["Structure Loot Settings"]
	# Determine the chance with which an item could be generated in any structures.
	#0.0 = 0% ~ 1.0 = 100%
	sulfurDust = 0.25
	saltpeterDust = 0.25
	netheriteScrapDust = 0.05
	netheriteDust = 0.05
	garlic = 0.4
	copperCrackHammer = 0.15
	ironCrackHammer = 0.1
	steelCrackHammer = 0.08
	diamondNugget = 0.1
	copperDust = 0.25
	ironDust = 0.2
	goldDust = 0.2
	carbonDust = 0.4
	diamondDust = 0.1
	emeraldDust = 0.1
	steelDust = 0.2
	steelIngot = 0.1

