
["Roost Ultimate Config"]
	#Production Speed in Seconds
	"Roost Speed" = 15
	"Breeder Speed" = 20
	"Trainer Speed" = 5
	"Soul Extractor Speed" = 6
	"Soul Breeder Speed" = 25
	#             
	#             
	#Seeds Tier 1-9 and Vanilla is the XP Amount for the tiered Seeds.
	"Vanilla Seeds" = 20
	"Seeds Tier 1" = 100
	"Seeds Tier 2" = 200
	"Seeds Tier 3" = 400
	"Seeds Tier 4" = 700
	"Seeds Tier 5" = 1200
	"Seeds Tier 6" = 2000
	"Seeds Tier 7" = 3500
	"Seeds Tier 8" = 6000
	"Seeds Tier 9" = 10000
	#             
	#             
	#XP Tier 1-9 - is the needed XP Amount for a levelup for each Tier of Chicken.
	"XP Tier 1" = 500
	"XP Tier 2" = 2500
	"XP Tier 3" = 6000
	"XP Tier 4" = 15000
	"XP Tier 5" = 30000
	"XP Tier 6" = 65000
	"XP Tier 7" = 110000
	"XP Tier 8" = 160000
	"XP Tier 9" = 250000
	#             
	#             
	#Tier 1-9 - sets the maxlevel for each Tier of Chicken.
	"Max Level Tier 1" = 60
	"Max Level Tier 2" = 60
	"Max Level Tier 3" = 60
	"Max Level Tier 4" = 60
	"Max Level Tier 5" = 60
	"Max Level Tier 6" = 60
	"Max Level Tier 7" = 60
	"Max Level Tier 8" = 60
	"Max Level Tier 9" = 60

